branchForLesson_01
Star1725/TrainingAtGeekbrains pull request #1
Opened 2020-08-19 16:27 UTC by Star1725

В итоге унаследовал все три класса от одного, т.к. получалось много дублирующего кода
в переопределённых методах. Подумал, что так будет лучше. Заранее извиняюсь, что отошёл от условия

2020-08-21 13:39 UTC, DisterDE requested changes
Достаточно тяжело комментировать, так как задание разбито на таски, которые являются одним заданием и не требуют самостоятельной реализации.
Сделай одну цельную реализацию и будет возможность объективно поревьювить.

2020-08-21 13:39 UTC, DisterDE commented on src/com/geekbrains/javaCoreAdvancedLevel/lesson_01/additional_task/DayOfWeek.java
> +        else return "" + (40 - day.ordinal()*8);
Вот так писать точно не стоит.
Скобки -- наши друзья.

2020-08-21 13:39 UTC, DisterDE commented on src/com/geekbrains/javaCoreAdvancedLevel/lesson_01/task1/Jumping.java
> +    void jump();
Не очень понимаю этого метода. Мы просто прыгаем? А в чем смысл?

2020-08-21 13:39 UTC, DisterDE commented on src/com/geekbrains/javaCoreAdvancedLevel/Main.java
> +        MaterialObject[] myObjects = {new Human("Fry", 3, 1000),
Очень плохое название для чего-то.

2020-08-21 13:39 UTC, DisterDE commented on src/com/geekbrains/javaCoreAdvancedLevel/Main.java
> +        }
То есть просто побежать и прыгнуть? Без дороги или препятствия?

2020-08-21 13:39 UTC, DisterDE commented on src/com/geekbrains/javaCoreAdvancedLevel/Main.java
> +        Wall wall = new Wall(2);
Массив препятствий.

2020-08-21 13:39 UTC, DisterDE commented on src/com/geekbrains/javaCoreAdvancedLevel/Main.java
> +            wall.getMaterialObjectForJump(myObject);
Здесь должен быть вызов метода интерфейса препятствий.

2020-08-21 13:39 UTC, DisterDE commented on src/com/geekbrains/javaCoreAdvancedLevel/Main.java
> +        }
Не очень понятно назначение этого цикла.
По дефолту в классах и так флаг установлен на фолс.
Но даже если хочется вернуть выбывших, то это должно делаться не в методе мейн.

2020-08-21 13:39 UTC, DisterDE commented on src/com/geekbrains/javaCoreAdvancedLevel/lesson_01/task2_3_4/SportsObstacle.java
> +    }
Методы без реализации должны быть абстракт. В данном случае я вижу интерфейс, но как интерфейс он плох, потому что полиморфизм недоработан. В этом интерфейсе должен быть один метод для любого вида препятствий.

2020-08-21 13:39 UTC, DisterDE commented on src/com/geekbrains/javaCoreAdvancedLevel/lesson_01/task2_3_4/Wall.java
> +    }
Почему бы это не вынести в родителя, назвав как-нибудь нейтрально (размер)?

2020-08-21 13:39 UTC, DisterDE commented on src/com/geekbrains/javaCoreAdvancedLevel/lesson_01/task1/MaterialObject.java
> +        else System.out.println(this.getClass().getSimpleName() + " " + this.name + " jumped over wall " + wall.getHeight() + " meters high");
Глаза сломал, пока читал. Этот метод требует переработки и скобок вокруг блоков иф-елс

2020-08-21 13:39 UTC, DisterDE commented on src/com/geekbrains/javaCoreAdvancedLevel/lesson_01/task1/MaterialObject.java
> +        else System.out.println(this.getClass().getSimpleName() + " " + this.name + " ran a distance of " + track.getLength() + " meters");
То же, что и выше.

2020-08-21 13:39 UTC, DisterDE commented on src/com/geekbrains/javaCoreAdvancedLevel/lesson_01/task1/MaterialObject.java
> +        System.out.println(this.getClass().getSimpleName() + " " + this.name + " run");
Мы знаем имя этого класса. В чем смысл нам в классе вызывать два метода, выполнение которых будет занимать ресурсы, если мы и так видим это имя.
Эти методы нужны для рефлексии и на текущем уровне точно не требуются.

2020-08-21 15:33 UTC, Star1725 commented on src/com/geekbrains/javaCoreAdvancedLevel/lesson_01/additional_task/DayOfWeek.java
> +        else return "" + (40 - day.ordinal()*8);
я так понимаю вот эти скобки - {}

2020-08-21 15:35 UTC, Star1725 commented on src/com/geekbrains/javaCoreAdvancedLevel/Main.java
> +        MaterialObject[] myObjects = {new Human("Fry", 3, 1000),
MaterialObject - попытался как объединить кота, человека и робота. Согласен самому не нравится

2020-08-23 12:31 UTC, Star1725 commented on src/com/geekbrains/javaCoreAdvancedLevel/lesson_01/task1/MaterialObject.java
> +        System.out.println(this.getClass().getSimpleName() + " " + this.name + " run");
Мы знаем имя класса родителя, а через this.getClass().getSimpleName() + " " + this.name я в Main-е получаю имя класса наследника

2020-08-23 12:32 UTC, Star1725 commented on src/com/geekbrains/javaCoreAdvancedLevel/lesson_01/task1/MaterialObject.java
> +        else System.out.println(this.getClass().getSimpleName() + " " + this.name + " jumped over wall " + wall.getHeight() + " meters high");
Переработал, разбил на два метода

2020-08-23 12:33 UTC, Star1725 commented on src/com/geekbrains/javaCoreAdvancedLevel/lesson_01/task1/MaterialObject.java
> +        else System.out.println(this.getClass().getSimpleName() + " " + this.name + " ran a distance of " + track.getLength() + " meters");
Переработал, разбил на два метода

2020-08-23 12:35 UTC, Star1725 commented on src/com/geekbrains/javaCoreAdvancedLevel/lesson_01/task2_3_4/Wall.java
> +    }
убрал родительский класс для препатствий, сделал интерфейс

2020-08-23 12:36 UTC, Star1725 commented on src/com/geekbrains/javaCoreAdvancedLevel/lesson_01/task2_3_4/SportsObstacle.java
> +    }
убрал родительский класс для препатствий, сделал один метод

2020-08-23 12:38 UTC, Star1725 commented on src/com/geekbrains/javaCoreAdvancedLevel/Main.java
> +        Wall wall = new Wall(2);
убрал эти строчки

2020-08-23 12:38 UTC, Star1725 commented on src/com/geekbrains/javaCoreAdvancedLevel/Main.java
> +        }
убрал эти строчки

2020-08-23 12:39 UTC, Star1725 commented on src/com/geekbrains/javaCoreAdvancedLevel/Main.java
> +        MaterialObject[] myObjects = {new Human("Fry", 3, 1000),
переименовал в Рекрутов

2020-08-23 12:40 UTC, Star1725 commented on src/com/geekbrains/javaCoreAdvancedLevel/lesson_01/task1/Jumping.java
> +    void jump();
удалил это метод

2020-08-27 13:11 UTC, merged