branchForLesson_03_dev2
Star1725/TrainingAtGeekbrains pull request #4
Opened 2020-08-27 11:53 UTC by Star1725

в телефонную книгу добавляю не Map<String, List>, а контакт с полями

2020-08-28 09:25 UTC, DisterRU requested changes
На 4- я бы оценил.

2020-08-28 09:25 UTC, DisterRU commented on src/com/geekbrains/javaCoreAdvancedLevel/lesson_03_Collection/homework/task2/Contact.java
> +package com.geekbrains.javaCoreAdvancedLevel.lesson_03_Collection.homework.task2;
Пакеты через нижнее подчеркивание не называют.

2020-08-28 09:25 UTC, DisterRU commented on src/com/geekbrains/javaCoreAdvancedLevel/lesson_03_Collection/homework/task2/Contact.java
> +    private ArrayList<Integer> listPhoneNumber;
Если мы объявляем коллекцию, то должны это делать по интерфейсу, то есть List<Integer>, а не по реализации.

2020-08-28 09:25 UTC, DisterRU commented on src/com/geekbrains/javaCoreAdvancedLevel/lesson_03_Collection/homework/task2/Contact.java
> +        System.out.println("         тел. номер " + (this.listPhoneNumber.indexOf(phoneNum) + 1) + " = " + phoneNum);
Форматирование съехало.

2020-08-28 09:25 UTC, DisterRU commented on src/com/geekbrains/javaCoreAdvancedLevel/lesson_03_Collection/homework/task2/Contact.java
> +        for (Integer phoneNum : this.listPhoneNumber) {
this лишнее.

2020-08-28 09:25 UTC, DisterRU commented on src/com/geekbrains/javaCoreAdvancedLevel/lesson_03_Collection/homework/task2/Contact.java
> +        this.listPhoneNumber = listPhoneNumber;
Подразумевается, что кто-то должен этот лист создать, а это неправильно с точки зрения архитектуры.
Контакт должен быть самостоятельной сущностью, куда закидывают информацию и откуда достают, а не за который что-то делают где-то вне.

2020-08-28 09:25 UTC, DisterRU commented on src/com/geekbrains/javaCoreAdvancedLevel/lesson_03_Collection/homework/task2/Contact.java
> +        return listPhoneNumber;
Лист в контакте является скрытым хранилищем.
Его реализация не должна меняться во вне.
Только контакт должен управлять номером телефонов, а остальные уже просить этот контакт добавить или показать телефоны.
В твоем же случае получается, что кто угодно может получить этот объект и делать с ним что хочешь.
Не безопасно.

2020-08-28 09:25 UTC, DisterRU commented on src/com/geekbrains/javaCoreAdvancedLevel/lesson_03_Collection/homework/task2/Phonebook.java
> +        }
Логика усложнена и кое-где продублирована.
Если в методе в двух случаях из трех вызывается addNewContact, то почему бы не вынести тот один случай, когда он не вызывается, в условие?
И флаг тогда не понадобится.
Просто пишем что-нибудь вроде.
```
if (contactList.contains(contact) {
  ...
  return;
}
addNewContact(...)
```

2020-08-28 09:25 UTC, DisterRU commented on src/com/geekbrains/javaCoreAdvancedLevel/lesson_03_Collection/homework/task2/Phonebook.java
> +        contact.getListPhoneNumber().add(phoneNumber);
Здесь должно быть
```
contact.add(phoneNumber)
```
Мы не даем всем подряд управление нашими внутренними хранилищами данных.

2020-08-28 09:25 UTC, DisterRU commented on src/com/geekbrains/javaCoreAdvancedLevel/lesson_03_Collection/homework/task2/Phonebook.java
> +        contactList.add(new Contact(lastName, new ArrayList<>(Arrays.asList(phoneNumber))));
```
contactList.add(new Contact(lastName, phoneNumber))
```
А уже сам контакт должен разбираться с добавлением этого номера куда ему нужно.

2020-08-28 09:25 UTC, DisterRU commented on src/com/geekbrains/javaCoreAdvancedLevel/lesson_03_Collection/homework/task2/Phonebook.java
> +        }
Нет никакой логики в случае отсутствия контакта.
Ни ошибки, ни сообщения об ошибке.

2020-09-01 21:13 UTC, Star1725 commented on src/com/geekbrains/javaCoreAdvancedLevel/lesson_03_Collection/homework/task2/Contact.java
> +package com.geekbrains.javaCoreAdvancedLevel.lesson_03_Collection.homework.task2;
исправил

2020-09-01 21:13 UTC, Star1725 commented on src/com/geekbrains/javaCoreAdvancedLevel/lesson_03_Collection/homework/task2/Contact.java
> +    private ArrayList<Integer> listPhoneNumber;
поправил

2020-09-01 21:13 UTC, Star1725 commented on src/com/geekbrains/javaCoreAdvancedLevel/lesson_03_Collection/homework/task2/Contact.java
> +        return listPhoneNumber;
В классе Contact у Хранилища удалил get и set

2020-09-01 21:13 UTC, Star1725 commented on src/com/geekbrains/javaCoreAdvancedLevel/lesson_03_Collection/homework/task2/Contact.java
> +        this.listPhoneNumber = listPhoneNumber;
В классе Contact у Хранилища удалил get и set

2020-09-01 21:13 UTC, Star1725 commented on src/com/geekbrains/javaCoreAdvancedLevel/lesson_03_Collection/homework/task2/Contact.java
> +        System.out.println("         тел. номер " + (this.listPhoneNumber.indexOf(phoneNum) + 1) + " = " + phoneNum);
я специально сделал, что бы в консоли получше смотрелось

2020-09-01 21:13 UTC, merged